# -*- coding: utf-8 -*-
"""Overfitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DEd8sc8zTjWuVgNYgPQezdtvlX19aoO
"""

import matplotlib.pyplot as plt
import numpy as np

# Cố định random seed để kết quả chạy không bị thay đổi
np.random.seed(42)

# Tạo 12 điểm ngẫu nhiên cho tập huấn luyện
x_tr = np.sort(np.random.uniform(0, 4, 12))
# Tạo nhãn y kèm nhiễu Gaussian
y_tr = np.sin(x_tr) + np.random.normal(0, 0.2, len(x_tr))

# Tạo 200 điểm mượt cho tập kiểm thử trên đoạn [0, 4]
x_te = np.linspace(0, 4, 200)
y_te = np.sin(x_te)

# 1. Hàm chuyển đổi đặc trưng thành đa thức
def build_poly_matrix(raw_x, poly_degree):
    feat_matrix = np.ones((len(raw_x), 1))
    for p in range(1, poly_degree + 1):
        feat_matrix = np.column_stack((feat_matrix, raw_x**p))
    return feat_matrix


# 2. Hàm huấn luyện hồi quy tuyến tính (Dùng Ma trận giả nghịch đảo)
def train_linear_model(X_mat, y_vec):
    return np.linalg.pinv(X_mat) @ y_vec


# 3. Hàm dự đoán giá trị
def predict_values(X_mat, weights):
    return X_mat @ weights


# 4. Hàm tính sai số bình phương trung bình (MSE)
def compute_mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)


# 5. Hàm tự chia dữ liệu thành K phần (K-Fold Split)
def create_kfold_indices(num_samples, num_folds=4):
    indices = np.arange(num_samples)
    np.random.shuffle(indices)
    return np.array_split(indices, num_folds)

DEGREE_HIGH = 10

# Biến đổi đặc trưng đa thức bậc 10
X_tr_high = build_poly_matrix(x_tr, DEGREE_HIGH)
X_te_high = build_poly_matrix(x_te, DEGREE_HIGH)

# Huấn luyện mô hình
w_high = train_linear_model(X_tr_high, y_tr)

# Dự đoán và tính MSE
y_pred_tr_high = predict_values(X_tr_high, w_high)
y_pred_te_high = predict_values(X_te_high, w_high)

mse_tr_high = compute_mse(y_tr, y_pred_tr_high)
mse_te_high = compute_mse(y_te, y_pred_te_high)

print(f'=== MÔ HÌNH OVERFIT (BẬC {DEGREE_HIGH}) ===')
print(f'Train MSE: {mse_tr_high:.4f}')
print(f'Test MSE : {mse_te_high:.4f}')

K_FOLDS = 4
fold_groups = create_kfold_indices(len(x_tr), num_folds=K_FOLDS)

max_degree_search = 10
avg_cv_errors = []

# Duyệt qua các bậc từ 1 đến 10
for deg in range(1, max_degree_search + 1):
    fold_mses = []

    for fold_idx in range(K_FOLDS):
        val_idx = fold_groups[fold_idx]
        train_idx = np.setdiff1d(np.arange(len(x_tr)), val_idx)

        # Chia dữ liệu x, y
        x_cv_train, y_cv_train = x_tr[train_idx], y_tr[train_idx]
        x_cv_val, y_cv_val = x_tr[val_idx], y_tr[val_idx]

        # Biến đổi đa thức
        X_cv_tr = build_poly_matrix(x_cv_train, deg)
        X_cv_val = build_poly_matrix(x_cv_val, deg)

        # Huấn luyện & Đánh giá
        w_cv = train_linear_model(X_cv_tr, y_cv_train)
        y_cv_pred = predict_values(X_cv_val, w_cv)

        fold_mses.append(compute_mse(y_cv_val, y_cv_pred))

    # Sai số trung bình Cross-Validation cho bậc deg
    avg_cv_errors.append(np.mean(fold_mses))

# Chọn bậc có sai số CV nhỏ nhất
optimal_degree = np.argmin(avg_cv_errors) + 1
print(f'Bậc tối ưu chọn từ K-Fold CV: {optimal_degree}')

# Huấn luyện mô hình với bậc tối ưu tìm được ở Block 5
X_tr_opt = build_poly_matrix(x_tr, optimal_degree)
X_te_opt = build_poly_matrix(x_te, optimal_degree)

w_opt = train_linear_model(X_tr_opt, y_tr)
y_pred_te_opt = predict_values(X_te_opt, w_opt)
mse_te_opt = compute_mse(y_te, y_pred_te_opt)

print('=== KẾT QUẢ VỚI BẬC TỐI ƯU ===')
print(f'Test MSE với bậc {optimal_degree}: {mse_te_opt:.4f}')

plt.figure(figsize=(10, 6))

# Điểm dữ liệu Train
plt.scatter(
    x_tr, y_tr, color='crimson', label='Dữ liệu Train (Nhiễu)', zorder=5
)

# Đường Sin thực tế (Ground Truth)
plt.plot(x_te, y_te, 'k--', label='Hàm gốc sin(x)', alpha=0.7)

# Đường Overfit (Bậc 10)
plt.plot(
    x_te,
    y_pred_te_high,
    color='darkorange',
    label=f'Overfit (Bậc {DEGREE_HIGH})',
)

# Đường Tuned (Bậc tối ưu)
plt.plot(
    x_te,
    y_pred_te_opt,
    color='teal',
    linewidth=2,
    label=f'Đã Tối Ưu (Bậc {optimal_degree})',
)

plt.ylim(-3, 3)
plt.xlabel('X')
plt.ylabel('Y')
plt.title('So sánh Mô hình Hồi quy Đa thức: Overfitting vs K-Fold CV')
plt.legend()
plt.grid(True, linestyle=':', alpha=0.6)
plt.show()